### PR TITLE
fix(builtin): always symlink node_modules at `execroot/my_wksp/node_modules` even when running in runfiles

### LINKED ISSUE #1781: //internal/pkg_npm/test/linking:test fails on Windows with remote caching enabled
# 🐞 bug report

### Is this a regression?

No, the test is added recently

### Description

`//internal/pkg_npm/test/linking:test` will fail in a second run with remote caching enabled.

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1446#b6409cc9-0a26-4ddd-8828-74d639131091

## 🔬 Minimal Reproduction

```
bazel test //internal/pkg_npm/test/linking:test
bazel clean --expunge & rm -rf node_modules
bazel test //internal/pkg_npm/test/linking:test
```

## 🔥 Exception or Error

<pre><code>
Executing tests from //internal/pkg_npm/test/linking:test
-----------------------------------------------------------------------------
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '@scoped/bar'
Require stack:
- C:\b\s7rxdkmr\execroot\build_bazel_rules_nodejs\bazel-out\x64_windows-fastbuild\bin\internal\pkg_npm\test\linking\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\b\s7rxdkmr\execroot\build_bazel_rules_nodejs\bazel-out\x64_windows-fastbuild\bin\internal\pkg_npm\test\linking\main.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\b\\s7rxdkmr\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\bin\\internal\\pkg_npm\\test\\linking\\main.js'
  ]
}
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
3.0.0rc2
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
HEAD
  </code>
</pre>

### PR DESCRIPTION
**Pull request by gregmagolan**
Fixes #1781.

Under runfiles, the linker should symlink node_modules at `execroot/my_wksp` so that when there are no runfiles (default on Windows) and scripts run out of `execroot/my_wksp` they can resolve node_modules with standard node_module resolution.

Also, restore BAZEL_WORKSPACE name environment variable. The optimization of deriving the workspace name from the path does not work on RBE. While we can derive the workspace from the pwd when running locally because it is in the execroot path `execroot/my_wksp`, on RBE the `execroot/my_wksp` path is reduced a path such as `/w/f/b` so the workspace name is obfuscated from the path. So we provide the workspace name here as an environment variable avaiable to all actions for the runfiles helpers to use.

### CODE REVIEW

**Comment by gregmagolan** [comment]
Noting here that I tested manually on my Windows laptop to verify that this resolves #1781.

File: internal/linker/link_node_modules.ts [hunk 1]
```diff
@@ -90,49 +90,71 @@ async function symlink(target: string, p: string): Promise<boolean> {
...
+  // `execroot/my_wksp` they can resolve node_modules with standard node_module resolution
+
+  // Look for bazel-out which is used to determine the the path to `execroot/my_wksp`. This works in
+  // all cases including on rbe where the execroot is a path such as `/b/f/w`. For example, when in
+  // runfiles on rbe, bazel runs the process in a directory such as
+  // `/b/f/w/bazel-out/k8-fastbuild/bin/path/to/pkg/some_test.sh.runfiles/my_wksp`. From here we can
+  // determine the execroot `b/f/w` by finding the first instance of bazel-out.
+  const match = startCwd.match(/\/bazel-out\//);
+  if (!match) {
+    panic('No bazel-out folder found in path!')
```
Comment (alexeagle) [inline internal/linker/link_node_modules.ts:126]: nit: include more info about what path we looked in?

File: internal/linker/link_node_modules.ts [hunk 2]
```diff
@@ -90,49 +90,71 @@ async function symlink(target: string, p: string): Promise<boolean> {
...
-
-  if (runfiles.execroot) {
-    // Under execroot there is an external folder in the root which look
-    // like 'my_wksp/external/npm/node_modules'
-    return path.join('external', root);
-  } else {
-    // Under runfiles, the repository should be layed out in the parent directory
-    // since bazel sets our working directory to the repository where the build is happening
-    return root;
+  if (fromManifest)
```
Comment (alexeagle) [inline internal/linker/link_node_modules.ts:142]: nit: wants braces

File: internal/linker/link_node_modules.ts [hunk 3]
```diff
@@ -485,11 +512,28 @@ export async function main(args: string[], runfiles: Runfiles) {
...
 
-  // NB: resolveRoot will change the cwd when under runfiles to the runfiles root
-  const rootDir = await resolveRoot(root, runfiles);
+  // Bazel starts actions with pwd=execroot/my_wksp when under execroot or pwd=runfiles/my_wksp
+  // when under runfiles.
+  // Normalize the slashes in startCwd for easier matching and manipulation.
+  const startCwd = process.cwd().replace(/\\/g, '/');
+  log_verbose('startCwd', startCwd);
+
+  // We can derive if the process is being run in the execroot if there is a bazel-out folder.
```
Comment (alexeagle) [inline internal/linker/link_node_modules.ts:521]: this is a different mechanism than in your other PR where you check for `execroot` in the path. Is one better than the other?

File: internal/linker/link_node_modules.ts (hunk 2 above)
Comment (gregmagolan) [reply internal/linker/link_node_modules.ts:142]: 👍

File: internal/linker/link_node_modules.ts (hunk 1 above)
Comment (gregmagolan) [reply internal/linker/link_node_modules.ts:126]: 👍

File: internal/linker/link_node_modules.ts (hunk 3 above)
Comment (gregmagolan) [reply internal/linker/link_node_modules.ts:521]: Yes. Looking for `execroot` basename will not work in RBE. I'll fix up the other PR. Thanks!

Comment (gregmagolan) [reply internal/linker/link_node_modules.ts:521]: Actually, the other PR needs to change once it is rebased on top of this one after it lands since the location of the linker node_modules has moved here.

Comment (gregmagolan) [reply internal/linker/link_node_modules.ts:521]: https://github.com/bazelbuild/rules_nodejs/pull/1800 for future reference
