### PR TITLE
Changed calculation of outs in ts_project to support using rule outputs as srcs

### LINKED ISSUE #2504: Cannot use filegroup for srcs in ts_project
# 🐞 bug report

### Affected Rule

ts_project

### Is this a regression?

I don't think so

### Description

When using `srcs` in `ts_project`, using a filegroup causes the rule to be unable to find any TypeScript files. I'm pretty sure this is because `ts_project_macro` passes along sources to `_out_paths` which does not expand the filegroup. 

https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/typescript/internal/ts_project.bzl#L668

## 🔬 Minimal Reproduction

I've created a minimum repro in this repo https://github.com/tbezman/ts-project-repro . Note the comments over here https://github.com/tbezman/ts-project-repro/blob/master/some-package/BUILD.bazel#L18

## 🔥 Exception or Error

<pre><code>
ERROR: Traceback (most recent call last):
        File "/Users/terencebezman/Code/ts-project-repro/some-package/BUILD.bazel", line 15, column 11, in <toplevel>
                ts_project(
        File "/private/var/tmp/_bazel_terencebezman/d9e2260f83532a6e2ac3b769af8ce672/external/npm/@bazel/typescript/internal/ts_project.bzl", line 663, column 13, in ts_project_macro
                fail("""ts_project target "//{}:{}" is configured to produce no outputs.
Error in fail: ts_project target "//some-package:the_project" is configured to produce no outputs.

Note that ts_project must know the srcs in advance in order to predeclare the outputs.
Check the srcs attribute to see that some .ts files are present (or .js files with allow_js=True).
ERROR: Skipping '//some-package:the_project': no such target '//some-package:the_project': target 'the_project' not declared in package 'some-package' defined by /Users/terencebezman/Code/ts-project-repro/some-package/BUILD.bazel
WARNING: Target pattern parsing failed.
ERROR: no such target '//some-package:the_project': target 'the_project' not declared in package 'some-package' defined by /Users/terencebezman/Code/ts-project-repro/some-package/BUILD.bazel
INFO: Elapsed time: 0.138s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
</code></pre>

## 🌍  Your Environment

**Operating System: MacOS Big Sur**

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 4.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:38:50 2021 (1611214730)
Build timestamp: 1611214730
Build timestamp as int: 1611214730
  </code>
</pre>

**Rules_nodejs version:  3.2.1**

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by twheys**
Hi 👋 

Fixes #2504

The goal of this PR is to make ts_project support using output files from rules in srcs without breaking the pre-calculated outputs in the macro. I understand the outputs are calculated in the macro so that they can be set as outputs on the rule which exposes the output files via a Bazel label like `//path/to/package:out-file-name`.

My changes introduce a secondary calculation of out files in the implementation of the ts_project rule so that the resolved list of files from the context `ctx.files.srcs` can be used. This makes it possible to use targets in the srcs attribute that point to other rules instead of being locked into using `glob` and source files in the same package.

Example:
```
filegroup(
  name = "ts_files",
  srcs = glob(["**/*.ts"]),
)

ts_project(
  name = "js_files",
  srcs = ["ts_files"],
  ...
)
```

Please let me know if you have any feedback or would like any changes made.

### CODE REVIEW

File: packages/typescript/test/ts_project/filegroup/a.ts [hunk 1]
```diff
@@ -0,0 +1,5 @@
+export const a: string = 'hello';
+
+// Repro #2044
```
Comment (alexeagle) [inline packages/typescript/test/ts_project/filegroup/a.ts:3]: I think you can simplify this test case a bit, no need to duplicate coverage we already have somewhere else. just a one-line TS file would work here

File: packages/typescript/test/ts_project/filegroup/tsconfig-extended.json [hunk 2]
```diff
@@ -0,0 +1,4 @@
+// This file is an extra hop of indirection, regression test for #1754
```
Comment (alexeagle) [inline packages/typescript/test/ts_project/filegroup/tsconfig-extended.json:1]: again, can simplify

File: packages/typescript/test/ts_project/filegroup/tsconfig.json [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+        //    cd C:/b/uuxnwop3/execroot/build_bazel_rules_nodejs
+        //    SET COMPILATION_MODE=fastbuild
+        //    bazel-out/host/bin/external/npm/typescript/bin/tsc.bat -p packages/typescript/test/ts_project/b/tsconfig.json --outDir bazel-out/x64_windows-fastbuild/bin/packages/typescript/test/ts_project/b --declarationDir bazel-out/x64_windows-fastbuild/bin/packages/typescript/test/ts_project/b --bazel_node_modules_manifest=bazel-out/x64_windows-fastbuild/bin/packages/typescript/test/ts_project/b/_tsconfig.module_mappings.json
+        //  Execution platform: @local_config_platform//:host
+        //  packages/typescript/test/ts_project/b/b.ts(1,17): error TS6305: Output file 'C:/b/uuxnwop3/execroot/build_bazel_rules_nodejs/packages/typescript/test/ts_project/a/a.d.ts' has not been built from source file 'C:/b/uuxnwop3/execroot/build_bazel_rules_nodejs/packages/typescript/test/ts_project/a/a.ts'.
+        "outDir": "../../../../../bazel-out/x64_windows-fastbuild/bin/packages/typescript/test/ts_project/a",
```
Comment (alexeagle) [inline packages/typescript/test/ts_project/filegroup/tsconfig.json:18]: shouldn't be needed since we don't depend on the `ts_project/a` package?

File: packages/typescript/internal/ts_project.bzl [hunk 4]
```diff
@@ -358,6 +428,7 @@ def ts_project_macro(
         out_dir = None,
         root_dir = None,
         link_workspace_root = False,
+        js_outs = [],
```
Comment (alexeagle) [inline packages/typescript/internal/ts_project.bzl:431]: why is js_outs special here? can we avoid that?
if the user has more js_outs, they might also have more map_outs?

File: packages/typescript/internal/ts_project.bzl [hunk 5]
```diff
@@ -333,6 +361,48 @@ def _out_paths(srcs, outdir, rootdir, allow_js, ext_map):
...
+
+    exts = {
+        "*": ".js.map",
+        ".tsx": ".jsx.map",
+    } if preserve_jsx else {"*": ".js.map"}
+    return _out_paths(srcs, out_dir, root_dir, False, exts)
+
+def _calculate_typings_outs(srcs, typings_out_dir, root_dir, declaration, composite, allow_js):
+    typings_out = []
+    #    typings_out = [
```
Comment (alexeagle) [inline packages/typescript/internal/ts_project.bzl:387]: comment could be removed?

File: packages/typescript/internal/ts_project.bzl [hunk 6]
```diff
@@ -98,6 +122,19 @@ def _calculate_root_dir(ctx):
     )
 
 def _ts_project_impl(ctx):
+    srcs = [src.path for src in ctx.files.srcs]
+    typings_out_dir = ctx.attr.declaration_dir or ctx.attr.out_dir
+
+    # Recalculate outputs inside the rule implementation.
+    # The outs are first calculated in the macro in order to try to predetermine outputs so they can be declared as
+    # outputs on the rule. This provides the benefit of being able to reference an output file with a label.
+    # However, it is not possible to evaluate files in outputs other rules such as filegroup, therefore the outs a
```
Comment (alexeagle) [inline packages/typescript/internal/ts_project.bzl:131]: outputs other rules -> outputs of other rules
outs a -> outs are

File: packages/typescript/internal/ts_project.bzl [hunk 7]
```diff
@@ -98,6 +122,19 @@ def _calculate_root_dir(ctx):
...
+    # recalculated here.
+    js_outs = _declare_outputs(ctx, _calculate_js_outs(srcs, ctx.attr.out_dir, ctx.attr.root_dir, ctx.attr.allow_js, ctx.attr.preserve_jsx, ctx.attr.emit_declaration_only))
```
Comment (alexeagle) [inline packages/typescript/internal/ts_project.bzl:133]: I'm trying to convince myself that the outputs we declare here will always include all the outputs which were predeclared. obviously they share the _calculate implementations. And I think Bazel will error if a predeclared output isn't created by any actions in the implementation. This seems simple :)

File: packages/typescript/internal/ts_project.bzl [hunk 8]
```diff
@@ -64,6 +75,19 @@ def _join(*elements):
         return "/".join(segments)
     return "."
 
+def _relative_to_package(path, ctx):
```
Comment (alexeagle) [inline packages/typescript/internal/ts_project.bzl:78]: nit: on the 5.x branch we can just `load("@bazel_skylib//lib:paths.bzl"` to get the relativize helper, but maybe not enough code sharing that it's worth it

**Review by alexeagle — COMMENTED** [review]
Neat! generally looks great, thank you.

this PR targets 4.x which is pretty old. Should target `stable` or `5.x` instead

File: packages/typescript/internal/ts_project.bzl (hunk 7 above)
Comment (twheys) [reply packages/typescript/internal/ts_project.bzl:133]: The "predeclared_outpus" will only find src that end with ".ts" or ".tsx", if an input is a label pointing to a target, then they won't be predeclared. 
The predeclared outputs are provided in `ctx.outputs`, but Bazel is equally happen if you use `ctx.actions.declare_file` for the same file. It figures out it's a predeclared output file and returns the same file object.

File: packages/typescript/internal/ts_project.bzl (hunk 6 above)
Comment (twheys) [reply packages/typescript/internal/ts_project.bzl:131]: Will fix the comment

File: packages/typescript/internal/ts_project.bzl (hunk 5 above)
Comment (twheys) [reply packages/typescript/internal/ts_project.bzl:387]: Yeah, I am still working on getting all of the tests to pass. This is remnants from that.

File: packages/typescript/internal/ts_project.bzl (hunk 4 above)
Comment (twheys) [reply packages/typescript/internal/ts_project.bzl:431]: Hm, I am pretty sure is was one test build that passes in js_outs as an attribute. I think that's why I added it here. I don't have a strong opinion on this, although it could come in handy that if a use wants to predeclare some outputs that might be in a filegroup, that they can specify them here. I suppose the other outs could be derived from this. Let me know if you want me to proceed a particular way with this.

File: packages/typescript/test/ts_project/filegroup/a.ts (hunk 1 above)
Comment (twheys) [reply packages/typescript/test/ts_project/filegroup/a.ts:3]: Alright, I'll add a target to another package instead.

File: packages/typescript/internal/ts_project.bzl (hunk 7 above)
Comment (alexeagle) [reply packages/typescript/internal/ts_project.bzl:133]: yeah that matches my understanding also, SGTM

File: packages/typescript/internal/ts_project.bzl (hunk 4 above)
Comment (alexeagle) [reply packages/typescript/internal/ts_project.bzl]: let's not introduce a special case unless we know the use case for it, I'd rather keep the attribute list the same for now

**Comment by alexeagle** [comment]
can you rebase on 5.x and target that branch instead? 4.x is old (really it's still pointing to 4.0.0) and I'm about to cut 5.0.0-rc.0

**Comment by twheys** [comment]
Yeah - I can get this by early next week. No need to wait on this feature if you want to move forward with 5.x, though. I have a patched version that I am using which solves my needs so I don't need it urgently.

**Comment by twheys** [comment]
Sorry for the delay, got pulled away from this. Will rebase for 5.x

**Comment by twheys** [comment]
@alexeagle alright I rebased with 5.x which required a bit of code changes, but I can run `bazel build //packages/typescript/test/...` successfully locally now.

Could you please take a fresh look, since the commit has changed a bit since the previous iteration?

**Review by rayman1104 — COMMENTED** [review]
I needed the same thing while migrating from `ts_library`, so thanks, I already use your solution!
The only thing I needed to change: if we pass dict to `tsconfig` field and use label in srcs, the generated tsconfig.json fails to generate files list correctly. To fix that I've just changed `packages/typescript/index.bzl:405` line to `files = srcs`. But maybe there is a prettier solution.

File: packages/typescript/internal/ts_project.bzl (hunk 6 above)
Comment (alexeagle) [reply packages/typescript/internal/ts_project.bzl:122]: ?

File: packages/typescript/internal/ts_project.bzl [hunk 9]
```diff
@@ -274,21 +325,58 @@ def _replace_ext(f, ext_map):
...
-            out = _join(outdir, f[:f.rindex(".")].replace(rootdir_replace_pattern, "") + _replace_ext(f, ext_map))
+            out = _join(out_dir, f[:f.rindex(".")].replace(rootdir_replace_pattern, "") + _replace_ext(f, ext_map))
 
             # Don't declare outputs that collide with inputs
             # for example, a.js -> a.js
             if out != f:
                 outs.append(out)
     return outs
 
+def _calculate_js_outs(srcs, out_dir, root_dir, allow_js, preserve_jsx, emit_declaration_only):
```
Comment (alexeagle) [inline packages/typescript/internal/ts_project.bzl:341]: nit: I think it's a bit more descriptive to name these functions "predict_*_outs" rather than calculate...

**Review by alexeagle — COMMENTED** [review]
great, close to merging.
thanks for dealing with the branching, you had unlucky timing working on this just as we were closing in on 5.0

File: packages/typescript/test/ts_project/filegroup/BUILD.bazel [hunk 10]
```diff
@@ -0,0 +1,20 @@
...
+    extends = "//packages/typescript/test/ts_project:tsconfig-base.json",
+    tsconfig = "tsconfig.json",
+    visibility = ["//packages/typescript/test:__subpackages__"],
+    # Use @babel/parser since the package.json is required to resolve "typings" field
+    # Repro of #2044
+    deps = [
+        "@npm//@babel/parser",
+        "@npm//@babel/types",
+    ],
+)
```
[the remark this answers is not in the document]
Comment (twheys) [reply packages/typescript/test/ts_project/filegroup/BUILD.bazel:20]: Since c.js comes from a source in the filegroup and is therefore not predeclared as an output, so it can't be asserted by using a filegroup like in other test packages. If the ts_project rule builds, then that is a pretty good assertion, but if we want to check that `c.js` is output we would need to write a rule implementation that checks the files resolved by a sources attr. Is there an existing utility that does this?

File: packages/typescript/internal/ts_project.bzl [hunk 11]
```diff
@@ -4,7 +4,7 @@ load("@rules_nodejs//nodejs:providers.bzl", "DeclarationInfo", "declaration_info
 load("@build_bazel_rules_nodejs//:providers.bzl", "ExternalNpmPackageInfo", "run_node")
 load("@build_bazel_rules_nodejs//internal/linker:link_node_modules.bzl", "module_mappings_aspect")
 load(":ts_config.bzl", "TsConfigInfo")
-load(":validate_options.bzl", "ValidOptionsInfo", _validate_lib = "lib")
+load(":validate_options.bzl", "ValidOptionsInfo", _validate_lib = "lib", _VALIDATED_ATTRS = "VALIDATED_ATTRS")
```
[the remark this answers is not in the document]
Comment (twheys) [reply packages/typescript/internal/ts_project.bzl:7]: Ok, I'll move it into the lib struct

File: packages/typescript/internal/ts_project.bzl [hunk 12]
```diff
@@ -91,6 +103,30 @@ def _calculate_root_dir(ctx):
     )
 
 def _ts_project_impl(ctx):
+    srcs = [_relative_to_package(src.path, ctx) for src in ctx.files.srcs]
+
+    transpile = ctx.attr.transpile
```
[the remark this answers is not in the document]
Comment (twheys) [reply packages/typescript/internal/ts_project.bzl:108]: Alright, that's how i had it at first but found it a bit verbose, but i wasn't super keen on having a bunch of local variables either. Will change it back.

File: packages/typescript/internal/ts_project.bzl (hunk 9 above)
Comment (twheys) [reply packages/typescript/internal/ts_project.bzl:341]: This function is called twice, once in the macro to determine if outputs can be predeclared, and again inside the rule impl to determine the full list of output files. In the first case, I would agree that `predict` accurately describes it, but in the rule implementation it yields a full list of the outputs that will be generated by running node, so I would argue it's not making a prediction anymore at that point. I don't have a strong opinion on the naming here though, so if you prefer it to use the verb predict I'm okay with that.

File: packages/typescript/internal/validate_options.bzl [hunk 13]
```diff
@@ -52,24 +52,27 @@ def _validate_options_impl(ctx):
         ValidOptionsInfo(marker = marker),
     ]
 
+VALIDATED_ATTRS = {
```
[the remark this answers is not in the document]
Comment (twheys) [reply packages/typescript/internal/validate_options.bzl:55]: Yeah, I'll rename this to SHARED_ATTRS and write a comment

File: packages/typescript/test/ts_project/filegroup/BUILD.bazel [hunk 14]
```diff
@@ -0,0 +1,20 @@
...
+    srcs = glob(["*.ts"]),
+)
+
+ts_project(
+    srcs = [":srcs"],
+    composite = True,
+    extends = "//packages/typescript/test/ts_project:tsconfig-base.json",
+    tsconfig = "tsconfig.json",
+    visibility = ["//packages/typescript/test:__subpackages__"],
+    # Use @babel/parser since the package.json is required to resolve "typings" field
```
[the remark this answers is not in the document]
Comment (twheys) [reply packages/typescript/test/ts_project/filegroup/BUILD.bazel:14]: It gets composite = True from the base tsconfig.json so it's simpler to keep that setting here, unless you'd prefer I write a new tsconfig.json for this package? Let me know. I'll remove the babel parser from the deps.

**Comment by twheys** [comment]
@rayman1104 if there are ts(x) or json files coming in from other targets needed by the tsconfig rule, then yeah we'll probably have to just pass all of srcs to that rule. I'll make that change.

**Comment by twheys** [comment]
Changing `files = srcs` in the `write_tsconfig` attr lead to a test failure since files besides json and ts files were being passed to the tsconfig rule. I fixed this by moving the same filtering logic that was previously in `index.bzl` into `ts_config.bzl` inside the rule impl where the full list of files is available. Since this required some functions from `ts_library.bzl` which already imports from `ts_config.bzl`, I moved a lot of the "lib" utility functions into a separate bzl module to avoid a cyclic import.

**Comment by twheys** [comment]
@alexeagle I'm not sure how to fix this failing test (https://app.circleci.com/pipelines/github/bazelbuild/rules_nodejs/5516/workflows/4ed463a5-f399-4aca-908a-3f616f3a9cfd/jobs/64160)
Can you please provide some guidance on how to run it locally? I'm not finding any of the input files it's complaining about in the repo.

File: packages/typescript/internal/ts_project.bzl (hunk 6 above)
Comment (twheys) [reply packages/typescript/internal/ts_project.bzl]: Fixed now

**Comment by alexeagle** [comment]
The repro command is the title of that circle ci step. It's the examples/from_src failing

**Comment by alexeagle** [comment]
the bug is that something in this implementation works within the same workspace where it was declared (build_bazel_rules_nodejs) but fails when referenced from a build running in a different workspace (examples/from_source is a nested workspace)

the common cause is some pathing computation which references a package name but fails to account for its pair, the workspace name.

looking through the code here I think this is the likely culprit

```
def _relative_to_package(path, ctx):
    for prefix in (ctx.bin_dir.path, ctx.label.package):
        prefix += "/"
        if path.startswith(prefix):
            path = path[len(prefix):]
    return path
```
and I don't see where the corresponding logic is in the base commit.

**Comment by alexeagle** [comment]
I'd still like to add test coverage for this, and cleanup the small amount of code duplication between ts_utils.bzl and other code in this repo and in bazel-skylib. But it's an exciting feature and we're shipping a minor today so I'm comfortable landing this as-is.

Thanks @twheys for your hard work on this one, looking forward to more collaborations :)

**Review by alexeagle — APPROVED** [review]
